name: gym_tracker
description: A cross-platform gym tracking app built with Flutter.
publish_to: "none" # this prevents accidental publishing to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Common Flutter packages you might use
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2

flutter:

  # Enables Material Design 3 (used in your code)
  uses-material-design: true

  # Assets bundled with the app
  assets:
    - lib/data/exercises.csv
